---
format: gfm
execute:
  echo: false
metadata-files:
  - _metadata.yml
---

# {{< meta gh.repo >}}: {{< meta tagline >}}

{{< include /docs/includes/_badges.qmd >}}

This repository contains the source raw data and Python code to build the data
package for the DP-Next work package 3 population questionnaire. Personal data
is kept in [Git LFS](https://decisions.seedcase-project.org/why-git-lfs/) stores
within [GenomeDK](https://genome.au.dk) and no personal data is uploaded to
GitHub. Only metadata and documentation is publicly accessible.

Check out our [website]({{< meta links.site >}}) for more information, such as
the [metadata]({{< meta links.site >}}/docs/) on the data package and its
contents.

::: callout-tip
This data package was generated from the [Template Data
Package](https://github.com/seedcase-project/template-data-package) Seedcase
template :tada:
:::

## Contributing

Check out our [contributing document](CONTRIBUTING.md) for information on how to
contribute to the project, including how to set up your development environment.

Please note that this project is released with a [Contributor Code of
Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to
abide by its terms.

::: content-hidden
### Contributors

{{< include /docs/includes/_contributors.qmd >}}
:::

## Licensing

This project is licensed under the [MIT License](LICENSE.md).

## Licensing

Code in this project is licensed under the [MIT License](LICENSE-MIT.md). Data
in this project is licensed under the [CC0 License](LICENSE.md).

## Changelog

For a list of changes, see our [changelog](CHANGELOG.md) page.

## Citing

If you use this package in your work, please cite it as follows:

```{python}
#| output: asis

!uvx --quiet cffconvert --format apalike
```

Or as a BibTeX entry:

```{python}
!uvx --quiet cffconvert --format bibtex
```
